### ISSUE TITLE
bug: panic on admin api /v1/tenants/xxx/tables with share table

### ISSUE THREAD

**Issue by flaneur2020** [databendlabs/databend#16040]
**Summary**

i'm using this admin api `/tenants/xxx/tables` to monitor the statistics of the tables into prometheus.

but the log shows that it failed in the recent version.

this is the log output:

```
6877f625-0211-448e-8f06-60eaec00c1ed 2024-07-12T11:53:16.696285Z ERROR databend_common_tracing::panic_hook: panic_hook.rs:57 panicked at src/query/service/src/databases/share/share_database.rs:89:72:
called `Option::unwrap()` on a `None` value backtrace= panic.file=src/query/service/src/databases/share/share_database.rs panic.line=89 panic.column=72
panicked at src/query/service/src/databases/share/share_database.rs:89:72:
called `Option::unwrap()` on a `None` value
```

**Comment by flaneur2020** [comment]
@lichuang can you help take a look?
