### ISSUE TITLE
bug: Databend Iceberg TPCH Q1 Failed for assertion `left == right` failed

### ISSUE THREAD

**Issue by Xuanwo** [databendlabs/databend#16594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/databendlabs/databend/issues) and found no similar issues.

### Version

Databend Query v1.2.643-nightly-de0fd7b156(rust-1.81.0-nightly-2024-10-10T15:59:43.465350171Z)

Built from PR: https://github.com/databendlabs/databend/pull/16593

### What's Wrong?

SQL:

```sql
SELECT
        l_returnflag,
        l_linestatus,
        SUM(l_quantity) AS sum_qty,
        SUM(l_extendedprice) AS sum_base_price,
        SUM(l_extendedprice * (1 - l_discount)) AS sum_disc_price,
        SUM(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge,
        AVG(l_quantity) AS avg_qty,
        AVG(l_extendedprice) AS avg_price,
        AVG(l_discount) AS avg_disc,
        COUNT(*) AS count_order
FROM
        ctl."iceberg.tpch".lineitem
WHERE
        l_shipdate <= DATE '1998-12-01'
GROUP BY
        l_returnflag,
        l_linestatus
ORDER BY
        l_returnflag,
        l_linestatus;
```

Error

```shell
databend       | ==> /tmp/std-query.log <==
databend       | panicked at src/query/expression/src/converts/arrow/from.rs:76:9:
databend       | assertion `left == right` failed
databend       |   left: 6
databend       |  right: 7
databend       |    0: backtrace::backtrace::libunwind::trace
databend       |              at /home/ubuntu/.cargo/git/checkouts/backtrace-rs-fb1f822361417489/72265be/src/backtrace/libunwind.rs:116:5
databend       |       backtrace::backtrace::trace_unsynchronized
databend       |              at /home/ubuntu/.cargo/git/checkouts/backtrace-rs-fb1f822361417489/72265be/src/backtrace/mod.rs:66:5
databend       |       backtrace::backtrace::trace
databend       |              at /home/ubuntu/.cargo/git/checkouts/backtrace-rs-fb1f822361417489/72265be/src/backtrace/mod.rs:53:14
databend       |    1: databend_common_tracing::panic_hook::captures_frames
databend       |              at /home/ubuntu/data/databend/src/common/tracing/src/panic_hook.rs:66:5
databend       |       databend_common_tracing::panic_hook::backtrace
databend       |              at /home/ubuntu/data/databend/src/common/tracing/src/panic_hook.rs:75:9
databend       |       databend_common_tracing::panic_hook::log_panic
databend       |              at /home/ubuntu/data/databend/src/common/tracing/src/panic_hook.rs:47:25
databend       |    2: databend_common_tracing::panic_hook::set_panic_hook::{{closure}}
databend       |              at /home/ubuntu/data/databend/src/common/tracing/src/panic_hook.rs:33:9
databend       |    3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2078:9
databend       |       std::panicking::rust_panic_with_hook
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:804:13
databend       |    4: std::panicking::begin_panic_handler::{{closure}}
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:670:13
databend       |    5: std::sys::backtrace::__rust_end_short_backtrace
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/backtrace.rs:171:18
databend       |    6: rust_begin_unwind
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:661:5
databend       |    7: core::panicking::panic_fmt
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panicking.rs:74:14
databend       |    8: core::panicking::assert_failed_inner
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panicking.rs:410:17
databend       |    9: core::panicking::assert_failed
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panicking.rs:365:5
databend       |   10: databend_common_expression::converts::arrow::from::<impl databend_common_expression::block::DataBlock>::from_record_batch
databend       |              at /home/ubuntu/data/databend/src/query/expression/src/converts/arrow/from.rs:76:9
databend       |   11: databend_common_storages_parquet::parquet_rs::parquet_reader::utils::transform_record_batch
databend       |              at /home/ubuntu/data/databend/src/query/storages/parquet/src/parquet_rs/parquet_reader/utils.rs:76:26
databend       |   12: <databend_common_storages_iceberg::table_source::IcebergTableSource as databend_common_pipeline_core::processors::processor::Processor>::async_process::{{closure}}::{{closure}}
databend       |              at /home/ubuntu/data/databend/src/query/storages/iceberg/src/table_source.rs:127:29
databend       |       <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/framed.rs:49:27
databend       |       async_backtrace::frame::Frame::in_scope::{{closure}}
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/frame.rs:184:17
databend       |       std::thread::local::LocalKey<T>::try_with
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/local.rs:283:12
databend       |       std::thread::local::LocalKey<T>::with
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/local.rs:260:9
databend       |   13: async_backtrace::frame::active_frame::with
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/frame.rs:81:9
databend       |       async_backtrace::frame::Frame::in_scope
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/frame.rs:180:13
databend       |       <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/framed.rs:49:9
databend       |       <databend_common_storages_iceberg::table_source::IcebergTableSource as databend_common_pipeline_core::processors::processor::Processor>::async_process::{{closure}}
databend       |              at /home/ubuntu/data/databend/src/query/storages/iceberg/src/table_source.rs:119:5
databend       |   14: <core::pin::Pin<P> as core::future::future::Future>::poll
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/future/future.rs:123:9
databend       |       <fastrace::future::InSpan<T> as core::future::future::Future>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fastrace-0.7.2/src/future.rs:124:19
databend       |   15: databend_common_pipeline_core::processors::processor::ProcessorPtr::async_process::{{closure}}
databend       |              at /home/ubuntu/data/databend/src/query/pipeline/core/src/processors/processor.rs:193:32
databend       |   16: <core::pin::Pin<P> as core::future::future::Future>::poll
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/future/future.rs:123:9
databend       |       <core::pin::Pin<P> as core::future::future::Future>::poll
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/future/future.rs:123:9
databend       |       futures_util::future::future::FutureExt::poll_unpin
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/mod.rs:558:9
databend       |       <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/select.rs:114:35
databend       |   17: databend_query::pipelines::executor::processor_async_task::ProcessorAsyncTask::create::{{closure}}
databend       |              at /home/ubuntu/data/databend/src/query/service/src/pipelines/executor/processor_async_task.rs:117:56
databend       |   18: <core::pin::Pin<P> as core::future::future::Future>::poll
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/future/future.rs:123:9
databend       |       futures_util::future::future::FutureExt::poll_unpin
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/mod.rs:558:9
databend       |       <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/select.rs:118:35
databend       |   19: databend_query::pipelines::executor::processor_async_task::ProcessorAsyncTask::create::{{closure}}
databend       |              at /home/ubuntu/data/databend/src/query/service/src/pipelines/executor/processor_async_task.rs:136:64
databend       |   20: <databend_query::pipelines::executor::processor_async_task::ProcessorAsyncTask as core::future::future::Future>::poll::{{closure}}
databend       |              at /home/ubuntu/data/databend/src/query/service/src/pipelines/executor/processor_async_task.rs:202:45
databend       |       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9
databend       |       std::panicking::try::do_call
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40
databend       |       std::panicking::try
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19
databend       |       std::panic::catch_unwind
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14
databend       |   21: databend_common_base::runtime::catch_unwind::catch_unwind
databend       |              at /home/ubuntu/data/databend/src/common/base/src/runtime/catch_unwind.rs:47:11
databend       |   22: <databend_query::pipelines::executor::processor_async_task::ProcessorAsyncTask as core::future::future::Future>::poll
databend       |              at /home/ubuntu/data/databend/src/query/service/src/pipelines/executor/processor_async_task.rs:202:24
databend       |   23: <fastrace::future::InSpan<T> as core::future::future::Future>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fastrace-0.7.2/src/future.rs:124:19
databend       |   24: <databend_common_base::runtime::runtime_tracker::TrackingFuture<T> as core::future::future::Future>::poll
databend       |              at /home/ubuntu/data/databend/src/common/base/src/runtime/runtime_tracker.rs:143:9
databend       |   25: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/framed.rs:49:27
databend       |       async_backtrace::frame::Frame::in_scope::{{closure}}
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/frame.rs:184:17
databend       |       std::thread::local::LocalKey<T>::try_with
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/local.rs:283:12
databend       |       std::thread::local::LocalKey<T>::with
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/local.rs:260:9
databend       |   26: async_backtrace::frame::active_frame::with
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/frame.rs:81:9
databend       |       async_backtrace::frame::Frame::in_scope
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/frame.rs:180:13
databend       |       <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
databend       |              at /home/ubuntu/.cargo/git/checkouts/async-backtrace-9554bf0eaadc9fb8/dea4553/backtrace/src/framed.rs:49:9
databend       |       tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
databend       |       tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
databend       |       tokio::runtime::task::core::Core<T,S>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
databend       |   27: tokio::runtime::task::harness::poll_future::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
databend       |       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9
databend       |       std::panicking::try::do_call
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40
databend       |       std::panicking::try
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19
databend       |       std::panic::catch_unwind
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14
databend       |   28: tokio::runtime::task::harness::poll_future
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
databend       |   29: tokio::runtime::task::harness::Harness<T,S>::poll_inner
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
databend       |   30: tokio::runtime::task::harness::Harness<T,S>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
databend       |   31: tokio::runtime::task::raw::RawTask::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
databend       |       tokio::runtime::task::LocalNotified<S>::run
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:427:9
databend       |       tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:657:17
databend       |       tokio::runtime::coop::with_budget
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
databend       |       tokio::runtime::coop::budget
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
databend       |       tokio::runtime::scheduler::multi_thread::worker::Context::run_task
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:593:9
databend       |   32: tokio::runtime::scheduler::multi_thread::worker::Context::run
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:544:24
databend       |   33: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:509:21
databend       |       tokio::runtime::context::scoped::Scoped<T>::set
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/scoped.rs:40:9
databend       |   34: tokio::runtime::context::set_scheduler
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:9
databend       |       tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:504:9
databend       |       tokio::runtime::context::runtime::enter_runtime
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
databend       |   35: tokio::runtime::scheduler::multi_thread::worker::run
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:496:5
databend       |   36: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:462:45
databend       |       <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/task.rs:42:21
databend       |   37: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
databend       |       tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
databend       |       tokio::runtime::task::core::Core<T,S>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
databend       |   38: tokio::runtime::task::harness::poll_future::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
databend       |       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9
databend       |       std::panicking::try::do_call
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40
databend       |       std::panicking::try
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19
databend       |       std::panic::catch_unwind
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14
databend       |   39: tokio::runtime::task::harness::poll_future
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
databend       |   40: tokio::runtime::task::harness::Harness<T,S>::poll_inner
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
databend       |   41: tokio::runtime::task::harness::Harness<T,S>::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
databend       |   42: tokio::runtime::task::raw::RawTask::poll
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
databend       |       tokio::runtime::task::UnownedTask<S>::run
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:464:9
databend       |   43: tokio::runtime::blocking::pool::Task::run
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:160:9
databend       |       tokio::runtime::blocking::pool::Inner::run
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:518:17
databend       |   44: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
databend       |              at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:476:13
databend       |       std::sys::backtrace::__rust_begin_short_backtrace
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/backtrace.rs:155:18
databend       |   45: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:542:17
databend       |       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9
databend       |       std::panicking::try::do_call
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40
databend       |       std::panicking::try
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19
databend       |       std::panic::catch_unwind
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14
databend       |       std::thread::Builder::spawn_unchecked_::{{closure}}
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:541:30
databend       |       core::ops::function::FnOnce::call_once{{vtable.shim}}
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/ops/function.rs:250:5
databend       |   46: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9
databend       |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9
databend       |       std::sys::pal::unix::thread::Thread::new::thread_start
databend       |              at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/pal/unix/thread.rs:108:17
databend       |   47: <unknown>
databend       |   48: clone
databend       |                                                                                                                                                              databend       |
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Failed at `assert_eq!(schema.num_fields(), batch.num_columns());`

Seems the schema for table doesn't align with parquet file.
