### ISSUE TITLE
ci err: expr_in_window cause debug assert failed

### ISSUE THREAD

**Issue by TCeason** [databendlabs/databend#16943]
**Summary**

Test passed but assert failed. 

```txt
Running MySQL test for file: tests/sqllogictests/suites/query/window_function/expr_in_window.test ...
panicked at src/query/expression/src/filter/selector.rs:494:17:
assertion failed: matches!(return_type, DataType::Boolean |
    DataType::Nullable(box DataType::Boolean))
   0: backtrace::backtrace::libunwind::trace
             at /opt/rust/cargo/git/checkouts/backtrace-rs-fb1f822361417489-shallow/72265be/src/backtrace/libunwind.rs:116:5
      backtrace::backtrace::trace_unsynchronized
             at /opt/rust/cargo/git/checkouts/backtrace-rs-fb1f822361417489-shallow/72265be/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
             at /opt/rust/cargo/git/checkouts/backtrace-rs-fb1f822361417489-shallow/72265be/src/backtrace/mod.rs:53:14
   1: databend_common_tracing::panic_hook::captures_frames
             at /workspace/src/common/tracing/src/panic_hook.rs:67:5
      databend_common_tracing::panic_hook::backtrace
             at /workspace/src/common/tracing/src/panic_hook.rs:75:5
      databend_common_tracing::panic_hook::log_panic
             at /workspace/src/common/tracing/src/panic_hook.rs:48:25
   2: databend_common_tracing::panic_hook::set_panic_hook::{{closure}}
             at /workspace/src/common/tracing/src/panic_hook.rs:33:9
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2078:9
      std::panicking::rust_panic_with_hook
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:804:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:663:13
   5: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/backtrace.rs:171:18
   6: rust_begin_unwind
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:661:5
   7: core::panicking::panic_fmt
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panicking.rs:74:14
   8: core::panicking::panic
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panicking.rs:148:5
   9: databend_common_expression::filter::selector::Selector::process_expr
             at /workspace/src/query/expression/src/filter/selector.rs:494:17
      databend_common_expression::filter::selector::Selector::process_others
             at /workspace/src/query/expression/src/filter/selector.rs:378:35
  10: databend_common_expression::filter::selector::Selector::process_select_expr
             at /workspace/src/query/expression/src/filter/selector.rs:135:41
  11: databend_common_expression::filter::selector::Selector::select
             at /workspace/src/query/expression/src/filter/selector.rs:69:9
      databend_common_expression::filter::filter_executor::FilterExecutor::select
             at /workspace/src/query/expression/src/filter/filter_executor.rs:87:9
  12: databend_common_expression::filter::filter_executor::FilterExecutor::filter
             at /workspace/src/query/expression/src/filter/filter_executor.rs:79:28
  13: databend_query::pipelines::processors::transforms::hash_join::common::<impl databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState>::get_other_predicate_result_block
             at /workspace/src/query/service/src/pipelines/processors/transforms/hash_join/common.rs:99:28
  14: databend_query::pipelines::processors::transforms::hash_join::probe_join::left_join::<impl databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState>::process_left_or_full_join_block
             at /workspace/src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_join.rs:500:13
  15: databend_query::pipelines::processors::transforms::hash_join::probe_join::left_join::<impl databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState>::left_join_with_conjunct
             at /workspace/src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_join.rs:312:13
      databend_query::pipelines::processors::transforms::hash_join::result_blocks::<impl databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState>::result_blocks
             at /workspace/src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs:71:21
  16: databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState::probe_join
             at /workspace/src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs:297:9
  17: databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState::probe
             at /workspace/src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs:146:18
  18: databend_query::pipelines::processors::transforms::hash_join::transform_hash_join_probe::TransformHashJoinProbe::probe_hash_table
             at /workspace/src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs:479:27
  19: <databend_query::pipelines::processors::transforms::hash_join::transform_hash_join_probe::TransformHashJoinProbe as databend_common_pipeline_core::processors::processor::Processor>::process
             at /workspace/src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs:354:29
  20: databend_common_pipeline_core::processors::processor::ProcessorPtr::process
             at /workspace/src/query/pipeline/core/src/processors/processor.rs:169:9
  21: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task
             at /workspace/src/query/service/src/pipelines/executor/executor_worker_context.rs:169:9
      databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task
             at /workspace/src/query/service/src/pipelines/executor/executor_worker_context.rs:132:52
  22: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_single_thread
             at /workspace/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:406:35
  23: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_threads::{{closure}}::{{closure}}
             at /workspace/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:378:50
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40
      std::panicking::try
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19
      std::panic::catch_unwind
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14
  24: databend_common_base::runtime::catch_unwind::catch_unwind
             at /workspace/src/common/base/src/runtime/catch_unwind.rs:47:11
  25: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_threads::{{closure}}
             at /workspace/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:378:34
      databend_common_base::runtime::runtime_tracker::ThreadTracker::tracking_function::{{closure}}::{{closure}}
             at /workspace/src/common/base/src/runtime/runtime_tracker.rs:208:17
      databend_common_base::runtime::thread::Thread::named_spawn::{{closure}}
             at /workspace/src/common/base/src/runtime/thread.rs:78:21
      std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/backtrace.rs:155:18
  26: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:542:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40
      std::panicking::try
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19
      std::panic::catch_unwind
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:541:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/ops/function.rs:250:5
  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/pal/unix/thread.rs:108:17
  28: <unknown>
  29: <unknown>
```

**Comment by TCeason** [comment]
cc @forsaken628

**Comment by sundy-li** [comment]
It's fixed in the latest version, could you confirm it?

**Comment by TCeason** [comment]
> It's fixed in the latest version, could you confirm it?


In this action

https://github.com/databendlabs/databend/actions/runs/12022226447/job/33515660912#step:4:1

**Comment by TCeason** [comment]
> ```
> window_function/expr_in_window.test
> ```

In test https://github.com/databendlabs/databend/blob/41956d0cce54980a22fc7ae75e0628cb7c7ce842/tests/sqllogictests/suites/query/window_function/expr_in_window.test#L303 only one SQL need to return statement err .

But I try build a debug mode databend-query run this query:

```sql
:) SELECT lag([456],8,['abc']) OVER (PARTITION BY 10);
error: APIError: QueryFailed: [1006]invalid digit found in string while evaluating function `to_uint16('abc')` in expr `to_uint16()`, during run expr: `CAST(['abc'] AS Array(UInt16))`.

```

It's a normal failed, and not print debug assert bt.

**Comment by TCeason** [comment]
Not occurs
